version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./mockserver.client.net.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netversion/publish
  - cmd: dotnet publish ./mockserver.client.net/mockserver.client.net.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\mockserver.client.net\bin\Debug\netstandard2.0\publish'
   name: WebSite
   type: dll
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./mockserver.client.net.tests.unit/mockserver.client.net.tests.unit.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test ./mockserver.client.net.tests.unit/mockserver.client.net.tests.unit.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*]MockServer.Client.Net.Models.*"
  - cmd: bash coveralls.sh
on_finish :
  # any cleanup in here
deploy: off