version: '3.7'

services:
  mockserverhost:
    platform: linux/amd64
    image: mockserver/mockserver:5.15.0
    networks: 
            - integreationnetwork
    ports:
      - "1080:1080"
networks:
    integreationnetwork:
        # driver: bridge