/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// HttpClassCallback
    /// </summary>
    [DataContract]
        public partial class HttpClassCallback :  IEquatable<HttpClassCallback>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpClassCallback" /> class.
        /// </summary>
        /// <param name="delay">delay.</param>
        /// <param name="callbackClass">callbackClass.</param>
        public HttpClassCallback(Delay delay = default(Delay), string callbackClass = default(string))
        {
            this.Delay = delay;
            this.CallbackClass = callbackClass;
        }
        
        /// <summary>
        /// Gets or Sets Delay
        /// </summary>
        [DataMember(Name="delay", EmitDefaultValue=false)]
        public Delay Delay { get; set; }

        /// <summary>
        /// Gets or Sets CallbackClass
        /// </summary>
        [DataMember(Name="callbackClass", EmitDefaultValue=false)]
        public string CallbackClass { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpClassCallback {\n");
            sb.Append("  Delay: ").Append(Delay).Append("\n");
            sb.Append("  CallbackClass: ").Append(CallbackClass).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpClassCallback);
        }

        /// <summary>
        /// Returns true if HttpClassCallback instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpClassCallback to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpClassCallback input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Delay == input.Delay ||
                    (this.Delay != null &&
                    this.Delay.Equals(input.Delay))
                ) && 
                (
                    this.CallbackClass == input.CallbackClass ||
                    (this.CallbackClass != null &&
                    this.CallbackClass.Equals(input.CallbackClass))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Delay != null)
                    hashCode = hashCode * 59 + this.Delay.GetHashCode();
                if (this.CallbackClass != null)
                    hashCode = hashCode * 59 + this.CallbackClass.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
