/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// HttpRequest
    /// </summary>
    [DataContract]
    public partial class HttpRequest : IEquatable<HttpRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpRequest" /> class.
        /// </summary>
        /// <param name="body">body.</param>
        /// <param name="headers">headers.</param>
        /// <param name="cookies">cookies.</param>
        /// <param name="queryStringParameters">queryStringParameters.</param>
        /// <param name="path">path.</param>
        /// <param name="method">method.</param>
        /// <param name="secure">secure.</param>
        /// <param name="keepAlive">keepAlive.</param>
        public HttpRequest(string body = default(string), KeyToMultiValue headers = default(KeyToMultiValue), KeyToValue cookies = default(KeyToValue), KeyToMultiValue queryStringParameters = default(KeyToMultiValue), string path = default(string), string method = default(string), bool? secure = default(bool?), bool? keepAlive = default(bool?))
        {
            this.Body = body;
            this.Headers = headers;
            this.Cookies = cookies;
            this.QueryStringParameters = queryStringParameters;
            this.Path = path;
            this.Method = method;
            this.Secure = secure;
            this.KeepAlive = keepAlive;
        }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [DataMember(Name = "body", EmitDefaultValue = false)]
        public string Body { get; set; }

        /// <summary>
        /// Gets or Sets Headers
        /// </summary>
        [DataMember(Name = "headers", EmitDefaultValue = false)]
        public KeyToMultiValue Headers { get; set; }

        /// <summary>
        /// Gets or Sets Cookies
        /// </summary>
        [DataMember(Name = "cookies", EmitDefaultValue = false)]
        public KeyToValue Cookies { get; set; }

        /// <summary>
        /// Gets or Sets QueryStringParameters
        /// </summary>
        [DataMember(Name = "queryStringParameters", EmitDefaultValue = false)]
        public KeyToMultiValue QueryStringParameters { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        [DataMember(Name = "method", EmitDefaultValue = false)]
        public string Method { get; set; }

        /// <summary>
        /// Gets or Sets Secure
        /// </summary>
        [DataMember(Name = "secure", EmitDefaultValue = false)]
        public bool? Secure { get; set; }

        /// <summary>
        /// Gets or Sets KeepAlive
        /// </summary>
        [DataMember(Name = "keepAlive", EmitDefaultValue = false)]
        public bool? KeepAlive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpRequest {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Cookies: ").Append(Cookies).Append("\n");
            sb.Append("  QueryStringParameters: ").Append(QueryStringParameters).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Secure: ").Append(Secure).Append("\n");
            sb.Append("  KeepAlive: ").Append(KeepAlive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpRequest);
        }

        /// <summary>
        /// Returns true if HttpRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpRequest input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Body == input.Body ||
                    (this.Body != null &&
                    this.Body.Equals(input.Body))
                ) &&
                (
                    this.Headers == input.Headers ||
                    (this.Headers != null &&
                    this.Headers.Equals(input.Headers))
                ) &&
                (
                    this.Cookies == input.Cookies ||
                    (this.Cookies != null &&
                    this.Cookies.Equals(input.Cookies))
                ) &&
                (
                    this.QueryStringParameters == input.QueryStringParameters ||
                    (this.QueryStringParameters != null &&
                    this.QueryStringParameters.Equals(input.QueryStringParameters))
                ) &&
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) &&
                (
                    this.Method == input.Method ||
                    (this.Method != null &&
                    this.Method.Equals(input.Method))
                ) &&
                (
                    this.Secure == input.Secure ||
                    (this.Secure != null &&
                    this.Secure.Equals(input.Secure))
                ) &&
                (
                    this.KeepAlive == input.KeepAlive ||
                    (this.KeepAlive != null &&
                    this.KeepAlive.Equals(input.KeepAlive))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Body != null)
                    hashCode = hashCode * 59 + this.Body.GetHashCode();
                if (this.Headers != null)
                    hashCode = hashCode * 59 + this.Headers.GetHashCode();
                if (this.Cookies != null)
                    hashCode = hashCode * 59 + this.Cookies.GetHashCode();
                if (this.QueryStringParameters != null)
                    hashCode = hashCode * 59 + this.QueryStringParameters.GetHashCode();
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                if (this.Method != null)
                    hashCode = hashCode * 59 + this.Method.GetHashCode();
                if (this.Secure != null)
                    hashCode = hashCode * 59 + this.Secure.GetHashCode();
                if (this.KeepAlive != null)
                    hashCode = hashCode * 59 + this.KeepAlive.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
