/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// HttpOverrideForwardedRequest
    /// </summary>
    [DataContract]
    public partial class HttpOverrideForwardedRequest : IEquatable<HttpOverrideForwardedRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpOverrideForwardedRequest" /> class.
        /// </summary>
        /// <param name="delay">delay.</param>
        /// <param name="httpRequest">httpRequest.</param>
        public HttpOverrideForwardedRequest(Delay delay = default(Delay), HttpRequest httpRequest = default(HttpRequest))
        {
            this.Delay = delay;
            this.HttpRequest = httpRequest;
        }

        /// <summary>
        /// Gets or Sets Delay
        /// </summary>
        [DataMember(Name = "delay", EmitDefaultValue = false)]
        public Delay Delay { get; set; }

        /// <summary>
        /// Gets or Sets HttpRequest
        /// </summary>
        [DataMember(Name = "httpRequest", EmitDefaultValue = false)]
        public HttpRequest HttpRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpOverrideForwardedRequest {\n");
            sb.Append("  Delay: ").Append(Delay).Append("\n");
            sb.Append("  HttpRequest: ").Append(HttpRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonSerializer.Serialize(this, JsonSerializerOptionsContants.Default);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpOverrideForwardedRequest);
        }

        /// <summary>
        /// Returns true if HttpOverrideForwardedRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpOverrideForwardedRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpOverrideForwardedRequest input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Delay == input.Delay ||
                    (this.Delay != null &&
                    this.Delay.Equals(input.Delay))
                ) &&
                (
                    this.HttpRequest == input.HttpRequest ||
                    (this.HttpRequest != null &&
                    this.HttpRequest.Equals(input.HttpRequest))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Delay != null)
                    hashCode = hashCode * 59 + this.Delay.GetHashCode();
                if (this.HttpRequest != null)
                    hashCode = hashCode * 59 + this.HttpRequest.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
