/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// Verification
    /// </summary>
    [DataContract]
    public partial class Verification : IEquatable<Verification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Verification" /> class.
        /// </summary>
        /// <param name="httpRequest">httpRequest.</param>
        /// <param name="times">times.</param>
        public Verification(HttpRequest httpRequest = default(HttpRequest), VerificationTimes times = default(VerificationTimes))
        {
            this.HttpRequest = httpRequest;
            this.Times = times;
        }

        /// <summary>
        /// Gets or Sets HttpRequest
        /// </summary>
        [DataMember(Name = "httpRequest", EmitDefaultValue = false)]
        public HttpRequest HttpRequest { get; set; }

        /// <summary>
        /// Gets or Sets Times
        /// </summary>
        [DataMember(Name = "times", EmitDefaultValue = false)]
        public VerificationTimes Times { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Verification {\n");
            sb.Append("  HttpRequest: ").Append(HttpRequest).Append("\n");
            sb.Append("  Times: ").Append(Times).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Verification);
        }

        /// <summary>
        /// Returns true if Verification instances are equal
        /// </summary>
        /// <param name="input">Instance of Verification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Verification input)
        {
            if (input == null)
                return false;

            return
                (
                    this.HttpRequest == input.HttpRequest ||
                    (this.HttpRequest != null &&
                    this.HttpRequest.Equals(input.HttpRequest))
                ) &&
                (
                    this.Times == input.Times ||
                    (this.Times != null &&
                    this.Times.Equals(input.Times))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HttpRequest != null)
                    hashCode = hashCode * 59 + this.HttpRequest.GetHashCode();
                if (this.Times != null)
                    hashCode = hashCode * 59 + this.Times.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
