/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// HttpError
    /// </summary>
    [DataContract]
    public partial class HttpError : IEquatable<HttpError>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpError" /> class.
        /// </summary>
        /// <param name="delay">delay.</param>
        /// <param name="dropConnection">dropConnection.</param>
        /// <param name="responseBytes">responseBytes.</param>
        public HttpError(Delay delay = default(Delay), bool? dropConnection = default(bool?), string responseBytes = default(string))
        {
            this.Delay = delay;
            this.DropConnection = dropConnection;
            this.ResponseBytes = responseBytes;
        }

        /// <summary>
        /// Gets or Sets Delay
        /// </summary>
        [DataMember(Name = "delay", EmitDefaultValue = false)]
        public Delay Delay { get; set; }

        /// <summary>
        /// Gets or Sets DropConnection
        /// </summary>
        [DataMember(Name = "dropConnection", EmitDefaultValue = false)]
        public bool? DropConnection { get; set; }

        /// <summary>
        /// Gets or Sets ResponseBytes
        /// </summary>
        [DataMember(Name = "responseBytes", EmitDefaultValue = false)]
        public string ResponseBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HttpError {\n");
            sb.Append("  Delay: ").Append(Delay).Append("\n");
            sb.Append("  DropConnection: ").Append(DropConnection).Append("\n");
            sb.Append("  ResponseBytes: ").Append(ResponseBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonSerializer.Serialize(this, JsonSerializerOptionsContants.Default);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HttpError);
        }

        /// <summary>
        /// Returns true if HttpError instances are equal
        /// </summary>
        /// <param name="input">Instance of HttpError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HttpError input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Delay == input.Delay ||
                    (this.Delay != null &&
                    this.Delay.Equals(input.Delay))
                ) &&
                (
                    this.DropConnection == input.DropConnection ||
                    (this.DropConnection != null &&
                    this.DropConnection.Equals(input.DropConnection))
                ) &&
                (
                    this.ResponseBytes == input.ResponseBytes ||
                    (this.ResponseBytes != null &&
                    this.ResponseBytes.Equals(input.ResponseBytes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Delay != null)
                    hashCode = hashCode * 59 + this.Delay.GetHashCode();
                if (this.DropConnection != null)
                    hashCode = hashCode * 59 + this.DropConnection.GetHashCode();
                if (this.ResponseBytes != null)
                    hashCode = hashCode * 59 + this.ResponseBytes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
