/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// VerificationTimes
    /// </summary>
    [DataContract]
    public sealed partial class VerificationTimes : IEquatable<VerificationTimes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerificationTimes" /> class.
        /// </summary>
        /// <param name="atLeast">atLeast.</param>
        /// <param name="atMost">atMost.</param>
        public VerificationTimes(int? atLeast = default(int?), int? atMost = default(int?))
        {
            this.AtLeast = atLeast;
            this.AtMost = atMost;
        }

        /// <summary>
        /// Gets or Sets AtLeast
        /// </summary>
        [DataMember(Name = "atLeast", EmitDefaultValue = false)]
        public int? AtLeast { get; set; }

        /// <summary>
        /// Gets or Sets AtMost
        /// </summary>
        [DataMember(Name = "atMost", EmitDefaultValue = false)]
        public int? AtMost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VerificationTimes {\n");
            sb.Append("  AtLeast: ").Append(AtLeast).Append("\n");
            sb.Append("  AtMost: ").Append(AtMost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, JsonSerializerOptionsConstants.Default);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerificationTimes);
        }

        /// <summary>
        /// Returns true if VerificationTimes instances are equal
        /// </summary>
        /// <param name="input">Instance of VerificationTimes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerificationTimes input)
        {
            if (input == null)
                return false;

            return
                (
                    this.AtLeast == input.AtLeast ||
                    (this.AtLeast != null &&
                    this.AtLeast.Equals(input.AtLeast))
                ) &&
                (
                    this.AtMost == input.AtMost ||
                    (this.AtMost != null &&
                    this.AtMost.Equals(input.AtMost))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AtLeast != null)
                    hashCode = hashCode * 59 + this.AtLeast.GetHashCode();
                if (this.AtMost != null)
                    hashCode = hashCode * 59 + this.AtMost.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
        
        public static VerificationTimes Once => new VerificationTimes(1, 1);
        public static VerificationTimes Twice => new VerificationTimes(1, 1);
        public static VerificationTimes Exactly(int specificNumberOfTimes) => new VerificationTimes(specificNumberOfTimes, specificNumberOfTimes);
    }
}
