/* 
 * Mock Server API
 *
 * MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.
 *
 * OpenAPI spec version: 5.6.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace MockServer.Client.Net.Models
{
    /// <summary>
    /// VerificationSequence
    /// </summary>
    [DataContract]
    public sealed partial class VerificationSequence : IEquatable<VerificationSequence>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerificationSequence" /> class.
        /// </summary>
        /// <param name="httpRequests">httpRequests.</param>
        public VerificationSequence(List<HttpRequest> httpRequests = default(List<HttpRequest>))
        {
            this.HttpRequests = httpRequests;
        }

        /// <summary>
        /// Gets or Sets HttpRequests
        /// </summary>
        [DataMember(Name = "httpRequests", EmitDefaultValue = false)]
        public List<HttpRequest> HttpRequests { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VerificationSequence {\n");
            sb.Append("  HttpRequests: ").Append(HttpRequests).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, JsonSerializerOptionsConstants.Default);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VerificationSequence);
        }

        /// <summary>
        /// Returns true if VerificationSequence instances are equal
        /// </summary>
        /// <param name="input">Instance of VerificationSequence to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VerificationSequence input)
        {
            if (input == null)
                return false;

            return
                (
                    this.HttpRequests == input.HttpRequests ||
                    this.HttpRequests != null &&
                    input.HttpRequests != null &&
                    this.HttpRequests.SequenceEqual(input.HttpRequests)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HttpRequests != null)
                    hashCode = hashCode * 59 + this.HttpRequests.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
