name: publish

on:
  workflow_dispatch:
    
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
          
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Display version
        run: |
          echo SemVer: $SEMVER
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Pack nuget package
        run: dotnet pack src/mockserver.client.net/mockserver.client.net.csproj -p:Version='$SEMVER' -c Release
      - name: Push nuget package
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.MOCKSERVER_CLIENT_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json      